Traceback (most recent call last):
  File "C:\Users\Spher\OneDrive\Desktop\CS\AI\Image_Caption\image-captioning\main.py", line 78, in <module>
    eval()
  File "C:\Users\Spher\OneDrive\Desktop\CS\AI\Image_Caption\image-captioning\main.py", line 63, in eval
    print(f"Validation Loss: {avg_val_loss:.4f}", end='\t')
UnboundLocalError: local variable 'avg_val_loss' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Spher\OneDrive\Desktop\CS\AI\Image_Caption\image-captioning\main.py", line 78, in <module>
    eval()
  File "C:\Users\Spher\OneDrive\Desktop\CS\AI\Image_Caption\image-captioning\main.py", line 63, in eval
    print(f"Validation Loss: {avg_val_loss:.4f}", end='\t')
UnboundLocalError: local variable 'avg_val_loss' referenced before assignment